/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rmipeer;

import Interficies.IPeer;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Llango
 */
public class ChatGrupoWindow extends javax.swing.JFrame {

    /**
     * Creates new form ChatWindow
     */
    
    IPeer pOrigen;
    MainWindow mw;
    String nombre;
    ArrayList<IPeer> destino = new ArrayList<>();
    
    public ChatGrupoWindow(IPeer origen, String nombre, ArrayList<IPeer> destino, MainWindow mw) throws RemoteException {        
        pOrigen = origen;   
        initComponents();
        this.setVisible(true);
        this.mw = mw;
        this.destino = destino;
        this.nombre = nombre;
        usuarioChat.setText(origen.getName());  
        anadirTextMiembros();
        mw.addGrupo(nombre,this);
    }
    
    public ArrayList getMiembrosGrupo() throws RemoteException{
        System.out.println("Destinos que envio desde ChatGrupoWWindow");
        for(int i=0;i<destino.size()-1;i++){
            System.out.println("Elemento Destino: "+destino.get(i).getName());
        }
        return destino;
    }
    
    public void setMiembrosGrupo(ArrayList<IPeer> usuarios) throws RemoteException{
        destino = usuarios;
        anadirTextMiembros();
    }
    
    public void anadirMiembros() throws RemoteException{
        for(int i=0;i<destino.size();i++){
            setMiembro(destino.get(i));
        }
    }
    
    public void anadirTextMiembros() throws RemoteException{
        miembrosGrupo.setText("");
        System.out.println("Antes de pintar tamaño: "+destino.size());
        for(int i=0;i<destino.size();i++){
//            System.out.println("Pinto: "+destino.get(i).getName());
            miembrosGrupo.setText(miembrosGrupo.getText()+destino.get(i).getName() + "\n");
        }
    }
    
    public void setMiembro(IPeer p) throws RemoteException{
        System.out.println("Al añadir: "+destino.size());
        for(int i=0;i<destino.size()-1;i++){
            System.out.println("Elemento Destino: "+destino.get(i).getName());
        }
        destino.add(p);     
    }
    
    public void append(String text,IPeer origen) throws RemoteException{
            mensajes.append(origen.getName() + " said : " + text + "\n");        
    }

    public void pintarDestino() throws RemoteException{
        System.out.println("LISTA DESTINO");
        for(int i=0;i<destino.size();i++){
            System.out.println(destino.get(i).getName());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mensajes = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        miembrosGrupo = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        escribirMensaje = new javax.swing.JTextArea();
        enviarMensaje = new javax.swing.JButton();
        cerrarChat = new javax.swing.JButton();
        usuarioChat = new javax.swing.JLabel();
        anadirPersona = new javax.swing.JButton();
        salirChat1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        mensajes.setColumns(20);
        mensajes.setRows(5);
        jScrollPane1.setViewportView(mensajes);

        miembrosGrupo.setColumns(20);
        miembrosGrupo.setRows(5);
        jScrollPane2.setViewportView(miembrosGrupo);

        escribirMensaje.setColumns(20);
        escribirMensaje.setRows(5);
        escribirMensaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                escribirMensajeKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(escribirMensaje);

        enviarMensaje.setText("Enviar");
        enviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarMensajeActionPerformed(evt);
            }
        });

        cerrarChat.setText("Cerrar ventana");
        cerrarChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarChatActionPerformed(evt);
            }
        });

        anadirPersona.setText("Añadir persona");
        anadirPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirPersonaActionPerformed(evt);
            }
        });

        salirChat1.setText("Salirse del grupo");
        salirChat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirChat1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                                .addComponent(jScrollPane1))
                            .addComponent(enviarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cerrarChat, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anadirPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salirChat1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(usuarioChat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usuarioChat, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(anadirPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cerrarChat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(salirChat1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(enviarMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Este metodo deberia abrir la ventana al otro tipo
    private void enviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarMensajeActionPerformed
        try {
            // TODO add your handling code here:
            for(int i = 0; i < destino.size(); i++){
                destino.get(i).enviarMensajeGrupal(escribirMensaje.getText(),pOrigen,destino,nombre);                
            }
            mensajes.append("I : " + escribirMensaje.getText() + "\n");
            escribirMensaje.setText("");   
        } catch (RemoteException ex) {
            Logger.getLogger(ChatGrupoWindow.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_enviarMensajeActionPerformed


    private void cerrarChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarChatActionPerformed

        this.setVisible(false);        
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarChatActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
       //VK_RETURN

    }//GEN-LAST:event_formKeyPressed

    private void escribirMensajeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_escribirMensajeKeyPressed
        // TODO add your handling code here:
//        if(evt.getID() == 13){
//            returnSend();
//            escribirMensaje.setFocusable(true);
//            
//        }
    }//GEN-LAST:event_escribirMensajeKeyPressed

    private void anadirPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirPersonaActionPerformed
        // TODO add your handling code here:
        try {
            anadirPersona ap = new anadirPersona(pOrigen,destino,this,mw);
            ap.setVisible(true);
        }catch(RemoteException ex){
            Logger.getLogger(ChatGrupoWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_anadirPersonaActionPerformed

    private void salirChat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirChat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirChat1ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadirPersona;
    private javax.swing.JButton cerrarChat;
    private javax.swing.JButton enviarMensaje;
    private javax.swing.JTextArea escribirMensaje;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea mensajes;
    private javax.swing.JTextArea miembrosGrupo;
    private javax.swing.JButton salirChat1;
    private javax.swing.JLabel usuarioChat;
    // End of variables declaration//GEN-END:variables
}
