/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rmipeer;

import Interficies.IPeer;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Llango
 */
public class ChatWindow extends javax.swing.JFrame {

    /**
     * Creates new form ChatWindow
     */
    
    IPeer pOrigen;
    MainWindow mw;
    
    ArrayList<IPeer> destino = new ArrayList<>();
    
    public ChatWindow(IPeer origen, IPeer destino, MainWindow mw) throws RemoteException {
        
        pOrigen = origen;   
        initComponents();
        this.setVisible(true);
        this.mw = mw;
        System.out.println("chat creado, eres " + origen.getName() + " y hablas con " + destino.getName());
        usuarioChat.setText(origen.getName());  
        setMiembro(destino);
        setTextMiembro(destino.getName());
    }
    
    public void setMiembro(IPeer p){
        destino.add(p);     
    }
    
    public void setTextMiembro(String name){
          miembrosGrupo.setText(name + "\n");
    }
    
    public void append(String text,IPeer origen) throws RemoteException{
            mensajes.append(origen.getName() + " said : " + text + "\n");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mensajes = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        miembrosGrupo = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        escribirMensaje = new javax.swing.JTextArea();
        enviarMensaje = new javax.swing.JButton();
        salirChat = new javax.swing.JButton();
        usuarioChat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        mensajes.setColumns(20);
        mensajes.setRows(5);
        jScrollPane1.setViewportView(mensajes);

        miembrosGrupo.setColumns(20);
        miembrosGrupo.setRows(5);
        jScrollPane2.setViewportView(miembrosGrupo);

        escribirMensaje.setColumns(20);
        escribirMensaje.setRows(5);
        escribirMensaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                escribirMensajeKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(escribirMensaje);

        enviarMensaje.setText("Enviar");
        enviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarMensajeActionPerformed(evt);
            }
        });

        salirChat.setText("Salir");
        salirChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirChatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enviarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salirChat, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(usuarioChat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usuarioChat, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enviarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(salirChat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Este metodo deberia abrir la ventana al otro tipo
    private void enviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarMensajeActionPerformed
        try {
            // TODO add your handling code here:
            for(int i = 0; i < destino.size(); i++){
                destino.get(i).enviarMensaje(escribirMensaje.getText(),pOrigen);                
            }
            //del mensaje de momento me olvido
            mensajes.append("I : " + escribirMensaje.getText() + "\n");
            escribirMensaje.setText("");   
        } catch (RemoteException ex) {
            Logger.getLogger(ChatWindow.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_enviarMensajeActionPerformed


    private void salirChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirChatActionPerformed
        try {
            //elimino la conversa con el peer destino
            for(int i = 0; i < destino.size(); i++){
                mw.eliminaConversacion(destino.get(i));                
            }                        
        } catch (RemoteException ex) {
            Logger.getLogger(ChatWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);        
        // TODO add your handling code here:
    }//GEN-LAST:event_salirChatActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
       //VK_RETURN

    }//GEN-LAST:event_formKeyPressed

    private void escribirMensajeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_escribirMensajeKeyPressed
        // TODO add your handling code here:
//        if(evt.getID() == 13){
//            returnSend();
//            escribirMensaje.setFocusable(true);
//            
//        }
    }//GEN-LAST:event_escribirMensajeKeyPressed

//        private void returnSend(){
//        try {
//            // TODO add your handling code here:
//            pDestino.enviarMensaje(escribirMensaje.getText(),pOrigen);
//            //del mensaje de momento me olvido
//            mensajes.append("I : " + escribirMensaje.getText());
//            System.out.println("I : " + escribirMensaje.getText());
//            escribirMensaje.setText("");
//            
//            
//        } catch (RemoteException ex) {
//            Logger.getLogger(ChatWindow.class.getName()).log(Level.SEVERE, null, ex);
//        }        
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviarMensaje;
    private javax.swing.JTextArea escribirMensaje;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea mensajes;
    private javax.swing.JTextArea miembrosGrupo;
    private javax.swing.JButton salirChat;
    private javax.swing.JLabel usuarioChat;
    // End of variables declaration//GEN-END:variables
}
